# 名称：blblHD
# 功能：解锁哔哩哔哩大会员高帧率权限
# 原作者：RuCu6
# 现作者：GitHub-YungHsin
# 重写链接：https://raw.githubusercontent.com/GitHub-YungHsin/QuantumultX/main/Rewrite/blblHD.conf

^http[s]?:\/\/((app|api)\.(\w{2,15})?\.(com|cn)).*player\.(v3|v2|v1).Play(URL|View).*$ url script-request-header https://raw.githubusercontent.com/GitHub-YungHsin/QuantumultX/main/Scripts/blblHD.js

hostname = *.biliapi.*, *.bilibili.*


#js脚本文件：https://raw.githubusercontent.com/GitHub-YungHsin/QuantumultX/main/Scripts/blblHD.js